### ISSUE TITLE
Rozmiar populacji

### ISSUE THREAD

**Issue by vladkyr** [AmandaBloom/Optical-Network-with-Evolutionary-Algorithm-Optimization#11]
Czemu liczba osobników w populacji zwiększa się od 10 do 40?

**Comment by vladkyr** [comment]
Czy to jest pożądane w algorytmie ewolucyjnym (strategii ewolucyjnej w danym przypadku)?
Czy może jednak wielkość populacji musi być równa wielkości początkowej populacji?

**Comment by AmandaBloom** [comment]
Mutacja jest mało prawdopodobna do uzyskania dobrego osobnika, więc murowane osobniki dodajemy do loga rozmiaru populacji przed selekcją, rozmiar populacji po selekcji to 10

**Comment by AmandaBloom** [comment]
Boje się że jak zaczniemy mutować losowo populacja nie będzie spełniać warunków.
