### ISSUE TITLE
Dodać mutacje w algorytmie

### ISSUE THREAD

**Issue by vladkyr** [AmandaBloom/Optical-Network-with-Evolutionary-Algorithm-Optimization#4]

**Comment by vladkyr** [comment]
"change path operator" odpowiada za mutacje w artykule

**Comment by AmandaBloom** [comment]
![image](https://user-images.githubusercontent.com/62996467/174460756-e9017d5d-5f30-4f02-87ca-d27ddd487b69.png)
Tak to zrobił mój kumpel, średnio to widzę, zobaczymy czy jakoś inaczej wykombinuję

**Comment by vladkyr** [comment]
Jeszcze raz przeanalizowałem podejście w artykulę i moim zdaniem ono jest lepsze. Patrząc na nasze zadanie, nie musimy robić wszystko dokładnie jak w artykule, tylko możemy zrobić pewne założenia dla uproszczenia (np. chromosom nie musi od razu wybierać konkretny transponder i nie musimy używać frequency slices). Dla każdego zapotrzebowanie (demand) definiujemy kilka dozwolonych ścieżek od miasta A do B. Nasz chromosom musi wybrać tylko jedną ścieżkę dla każdego demandu i wtedy przy mutacji/krzyżowaniu/selekcji nie musimy się zastanawiać czy to jest dopuszczalne rozwiązanie, tylko sumujemy wszystkie zapotrzebowania na danej krawędzi pomiędzy 2 miastami i wybieramy najtańszy zestaw transponderów dla spełnienia tej sumy zapotrzebowań
